export class Starship{
  MGTL:string;
  cargo_capacity:string;
  consumables:string;
  cost_in_credits:string;
  created:string;
  crew:string;
  edited:string;
  hyperdrive:string;
  length:string;
  manufacturer:string;
  max_atmosphering_speed:string;
  model:string;
  name:string;
  passegers:string;
  films:string[];
  pilots:string[];
  starship_class:string;
  url:string;
}
